package com.gourmetoven.gourmetapp.util;

public class TestConstants {

    private TestConstants() {
    }

    public static final String ingredientsExpected = "[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":102,\"ingredientName\":\"Paprika\",\"type\":\"vegetarian\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\",\"type\":\"non-vegetarian\"},{\"ingredientId\":104,\"ingredientName\":\"Pineapple\",\"type\":\"vegetarian\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"},{\"ingredientId\":107,\"ingredientName\":\"Salmon\",\"type\":\"non-vegetarian\"},{\"ingredientId\":108,\"ingredientName\":\"Onion\",\"type\":\"vegetarian\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\",\"type\":\"vegetarian\"},{\"ingredientId\":110,\"ingredientName\":\"Chicken\",\"type\":\"non-vegetarian\"},{\"ingredientId\":111,\"ingredientName\":\"Egg\",\"type\":\"non-vegetarian\"},{\"ingredientId\":112,\"ingredientName\":\"Mustard\",\"type\":\"vegetarian\"},{\"ingredientId\":113,\"ingredientName\":\"Lettuce\",\"type\":\"vegetarian\"}]";

    public static final String recipesExpected_All_Deafult = "[{\"recipeId\":104,\"recipeName\":\"Omlette\",\"servings\":5,\"dishType\":\"non-vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\",\"type\":\"vegetarian\"},{\"ingredientId\":111,\"ingredientName\":\"Egg\",\"type\":\"non-vegetarian\"}],\"instructions\":[\"Lots of Garlic\",\"No Paprika\"]},{\"recipeId\":107,\"recipeName\":\"Potato stew\",\"servings\":1,\"dishType\":\"vegetarian\",\"creationType\":\"user-defined\",\"owningUser\":\"Thomas\",\"ingredients\":[{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"}],\"instructions\":[\"Lots of potatos\"]},{\"recipeId\":106,\"recipeName\":\"Spanish Omlette\",\"servings\":2,\"dishType\":\"non-vegetarian\",\"creationType\":\"user-defined\",\"owningUser\":\"Thomas\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":111,\"ingredientName\":\"Egg\",\"type\":\"non-vegetarian\"}],\"instructions\":[\"Two eggs\"]},{\"recipeId\":101,\"recipeName\":\"Pineapple Pizza\",\"servings\":4,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":104,\"ingredientName\":\"Pineapple\",\"type\":\"vegetarian\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"}],\"instructions\":[\"No Garlic\",\"No Paprika\",\"Lots of Pineapple\"]},{\"recipeId\":102,\"recipeName\":\"Salami Pizza\",\"servings\":2,\"dishType\":\"non-vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\",\"type\":\"non-vegetarian\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"}],\"instructions\":[]},{\"recipeId\":103,\"recipeName\":\"Potato Pizza\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\",\"type\":\"vegetarian\"},{\"ingredientId\":112,\"ingredientName\":\"Mustard\",\"type\":\"vegetarian\"}],\"instructions\":[]}]";
    public static final String recipesExpectedForType_Vegetarian = "[{\"recipeId\":107,\"recipeName\":\"Potato stew\",\"servings\":1,\"dishType\":\"vegetarian\",\"creationType\":\"user-defined\",\"owningUser\":\"Thomas\",\"ingredients\":[{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"}],\"instructions\":[\"Lots of potatos\"]},{\"recipeId\":101,\"recipeName\":\"Pineapple Pizza\",\"servings\":4,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":104,\"ingredientName\":\"Pineapple\",\"type\":\"vegetarian\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"}],\"instructions\":[\"No Garlic\",\"No Paprika\",\"Lots of Pineapple\"]},{\"recipeId\":103,\"recipeName\":\"Potato Pizza\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"},{\"ingredientId\":109,\"ingredientName\":\"Garlic\",\"type\":\"vegetarian\"},{\"ingredientId\":112,\"ingredientName\":\"Mustard\",\"type\":\"vegetarian\"}],\"instructions\":[]}]";

    public static final String recipeExpected_4_ALL_ExcludeSalami_Include_Instruction="[{\"recipeId\":101,\"recipeName\":\"Pineapple Pizza\",\"servings\":4,\"dishType\":\"vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":104,\"ingredientName\":\"Pineapple\",\"type\":\"vegetarian\"},{\"ingredientId\":106,\"ingredientName\":\"Salt\",\"type\":\"vegetarian\"}],\"instructions\":[\"No Garlic\",\"No Paprika\",\"Lots of Pineapple\"]}]";


    public static final String searchResult_2_nonVeg_Salami = "[{\"recipeId\":102,\"recipeName\":\"Salami Pizza\",\"servings\":2,\"dishType\":\"non-vegetarian\",\"creationType\":\"default\",\"owningUser\":\"system\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\",\"type\":\"non-vegetarian\"},{\"ingredientId\":105,\"ingredientName\":\"Potato\",\"type\":\"vegetarian\"}],\"instructions\":[]}]";

    public static final String
            recipeCreateResult = "{\"recipeId\":108,\"recipeName\":\"sambar\",\"servings\":2,\"dishType\":\"vegetarian\",\"creationType\":\"user-defined\",\"owningUser\":\"Thomas\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":102,\"ingredientName\":\"Paprika\",\"type\":\"vegetarian\"}],\"instructions\":[\"More spicy\"]}";

    public static final String recipeUpdateResult = "{\"recipeId\":108,\"recipeName\":\"Sambar\",\"servings\":6,\"dishType\":\"vegetarian\",\"creationType\":\"user-defined\",\"owningUser\":\"Thomas\",\"ingredients\":[{\"ingredientId\":101,\"ingredientName\":\"Cheese\",\"type\":\"vegetarian\"},{\"ingredientId\":102,\"ingredientName\":\"Paprika\",\"type\":\"vegetarian\"},{\"ingredientId\":103,\"ingredientName\":\"Salami\",\"type\":\"non-vegetarian\"}],\"instructions\":[\"Less spicy\",\"Less Garlic\"]}";
}